spring.application.name=campeonato

# URI para MongoDB Atlas (incluimos ambas para compatibilidad total)
spring.mongodb.uri=mongodb+srv://estivenarodriguez_db_user:EE4Jicu3fQ1RmSOY@cluster0.wmyslnx.mongodb.net/campeonato_db?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=campeonato_db
spring.data.mongodb.uri=mongodb+srv://estivenarodriguez_db_user:EE4Jicu3fQ1RmSOY@cluster0.wmyslnx.mongodb.net/campeonato_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=campeonato_db

# Puerto 8119 y soporte para Render
server.port=${PORT:8119}